### ISSUE TITLE
同时使用多个input框时，无法收起键盘

### ISSUE THREAD

**Issue by mengerzhuanyong** [lyxia/react-native-yusha-customKeyboard#9]
当一个页面同时使用多个input框时，从任意一个唤起键盘后，点击其他的输入框后无法点击完成收起键盘，只能回到最初唤起键盘的输入框内点击完成按钮才能收起键盘，还望解决一下！

**Comment by lyxia** [comment]
能给个gif吗




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            liuyunxia8
                            
                            
                                
                                    邮箱：liuyunxia8@gmail.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master
在2018年06月21日 20:28，mengerzhuanyong 写道： 当一个页面同时使用多个input框时，从任意一个唤起键盘后，点击其他的输入框后无法点击完成收起键盘，只能回到最初唤起键盘的输入框内点击完成按钮才能收起键盘，还望解决一下！

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/lyxia/react-native-yusha-customKeyboard/issues/9","url":"https://github.com/lyxia/react-native-yusha-customKeyboard/issues/9","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lyxia/react-native-yusha-customKeyboard","title":"lyxia/react-native-yusha-customKeyboard","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/lyxia/react-native-yusha-customKeyboard"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"同时使用多个input框时，无法收起键盘 (#9)"}],"action":{"name":"View Issue","url":"https://github.com/lyxia/react-native-yusha-customKeyboard/issues/9"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "同时使用多个input框时，无法收起键盘 (#9)",
"sections": [
{
"text": "",
"activityTitle": "**mengerzhuanyong**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@mengerzhuanyong",
"facts": [
{
"name": "Repository: ",
"value": "lyxia/react-native-yusha-customKeyboard"
},
{
"name": "Issue #: ",
"value": 9
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"lyxia/react-native-yusha-customKeyboard\",\n\"issueId\": 9,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"lyxia/react-native-yusha-customKeyboard\",\n\"issueId\": 9\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/lyxia/react-native-yusha-customKeyboard/issues/9"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 348643403\n}"
}
],
"themeColor": "26292E"
}

**Comment by mengerzhuanyong** [comment]
![qq20180629-171501-hd](https://user-images.githubusercontent.com/19523478/42084572-9f6abe5c-7bc0-11e8-9b9c-8989f0215353.gif)

**Comment by mengerzhuanyong** [comment]
@lyxia 就是上面这个情况

**Comment by lyxia** [comment]
![Uploading QQ20180630-173537.gif…]()

**Comment by lyxia** [comment]
![qq20180630-173537](https://user-images.githubusercontent.com/7269593/42123910-5627bf0c-7c8c-11e8-9f42-66b5d5417301.gif)

**Comment by lyxia** [comment]
我在运行https://github.com/lyxia/react-native-yusha-customKeyboard/tree/master/RNDemo时无法重现，以上是我的操作，你可以运行下demo看下效果

**Comment by lyxia** [comment]
我在运行https://github.com/lyxia/react-native-yusha-customKeyboard/tree/master/RNDemo 时无法重现，以上是我的操作，你可以运行下demo看下效果

**Comment by mengerzhuanyong** [comment]
嗯嗯！～我在看看！～
